'use strict';
// Editorial ideas and broad planning estimates, not marketplace listings or prices.
const gifts = [
 {id:'mug',title:'Their slow-morning mug',category:'An everyday ritual',interest:'food',min:15,max:40,occasions:['just','home'],description:'A handmade cup in their favorite color, paired with a note about taking the morning slowly.',why:'A familiar daily ritual is a useful starting point when you know how they like their coffee or tea.',check:'Check the size they use, handle comfort and dishwasher needs.',note:'For your first quiet five minutes of the day.'},
 {id:'letters',title:'A tiny archive of us',category:'A personal keepsake',interest:'stories',min:0,max:15,occasions:['anniversary','birthday'],description:'Three short letters: a memory, something you admire, and a small plan for another day.',why:'Specific memories give you something personal to say without guessing what they want to own.',check:'Keep the tone appropriate to your relationship. For a colleague, choose a simple thank-you instead.',note:'I still smile when I think about that afternoon.'},
 {id:'clay',title:'An afternoon with clay',category:'Something to experience',interest:'creative',min:35,max:100,occasions:['birthday','anniversary'],description:'A beginner pottery session, with room to make something gloriously imperfect.',why:'Experience-giving research offers a reason to consider something to do, if making things is already their idea of fun.',check:'Ask about dates, accessibility and whether they want company before booking.',note:'For the thing you keep saying you’d love to try.'},
 {id:'cutting',title:'A cutting from your favorite plant',category:'Something to grow',interest:'nature',min:0,max:15,occasions:['home','just'],description:'A rooted cutting in a reused jar, with a little care note in your own words.',why:'It connects their interest in plants with something you have taken time to prepare.',check:'Check plant toxicity around pets and children, and whether they actually want another plant.',note:'A little green company for your windowsill.'},
 {id:'book',title:'A book with a letter tucked inside',category:'For their next chapter',interest:'stories',min:10,max:30,occasions:['birthday','thanks'],description:'Choose from a genre they already enjoy. Add a removable note saying why you thought of them.',why:'Their reading preferences give you more to work with than a generic bestseller list.',check:'Make sure they do not already own it. Avoid writing on the book if they prefer clean pages.',note:'This made me think of our conversation about…'},
 {id:'vase',title:'A little home for one flower',category:'A useful little object',interest:'home',min:15,max:50,occasions:['home','thanks'],description:'A small bud vase that fits the shelf, color palette and space they actually have.',why:'Choosing for their real home makes the idea more personal than choosing for your own taste.',check:'Ask about their style if you are unsure. Check flower safety around pets.',note:'For a small bright spot in your new place.'},
 {id:'recipe',title:'The recipe you always ask for',category:'Made, not bought',interest:'food',min:0,max:10,occasions:['thanks','just'],description:'Write out a favorite recipe, including the tiny tricks that never make it into the instructions.',why:'A recipe they have asked about starts with an interest they have already expressed.',check:'Include ingredients clearly and take allergies or dietary preferences seriously.',note:'The secret is in the last five minutes. Now it’s yours.'},
 {id:'walk',title:'A walk with a very good ending',category:'Time, thoughtfully planned',interest:'nature',min:0,max:20,occasions:['birthday','just'],description:'Map a gentle local route ending at a favorite view. Offer two dates and let them choose.',why:'This offers time and attention around an interest they enjoy, without needing another possession.',check:'Choose a route that works for their mobility, weather and comfort. Keep it easy to decline.',note:'An afternoon outside, whenever you feel like it.'},
 {id:'sketch',title:'A pocket for their next idea',category:'For the maker',interest:'creative',min:10,max:25,occasions:['birthday','thanks'],description:'A pocket sketchbook or notebook in the paper style they actually use.',why:'A small tool can show you have noticed what they like making.',check:'Artists often have specific paper preferences. Check before choosing.',note:'For whatever you dream up next.'},
 {id:'playlist',title:'A soundtrack with liner notes',category:'Made, not bought',interest:'creative',min:0,max:0,occasions:['anniversary','just'],description:'Make a short playlist and explain, in a sentence per song, why each one belongs.',why:'The personal explanation makes your choices understandable instead of leaving them to guess.',check:'Use music they enjoy and a platform they can access. Keep romantic messages appropriate to the relationship.',note:'Track three is here because of that rainy drive.'},
 {id:'home-note',title:'A first-night welcome note',category:'Made, not bought',interest:'home',min:0,max:0,occasions:['home','thanks'],description:'A handwritten card with a favorite neighborhood tip and a specific offer to help them settle in.',why:'A practical offer can respond to what is happening in their life right now.',check:'Offer something you can actually do, and let them choose whether to accept.',note:'When you’re ready, I’d love to help with that bookshelf.'},
 {id:'memory',title:'One photo. The whole story.',category:'Made, not bought',interest:'stories',min:0,max:0,occasions:['anniversary','birthday'],description:'Send a photo you already share, alongside a short story about what you remember from that day.',why:'A concrete shared moment gives the message meaning without requiring a purchase.',check:'Choose a memory they also enjoy. Ask before sharing personal photos publicly.',note:'What I remember most is how much we laughed.'}
];
const relationshipNotes = {
 friend:'For a good friend: start with a running joke, a favorite ritual, or something they’ve mentioned wanting to try.',
 new:'For someone you’re dating: keep it light, personal and easy to accept. Avoid expensive gestures or assumptions about commitment.',
 partner:'For a long-term partner: use the details only you would notice. A shared memory or an invitation can be a starting point, not a substitute for everyday care.',
 family:'For family: leave room for who they are now, not just the role they play. Ask about a current interest.',
 colleague:'For a colleague: keep the message friendly and the gift modest. Consider workplace gift policies and avoid overly intimate wording.'
};
const occasionNotes={just:'A small gesture needs no big occasion.',birthday:'Make room for how they actually like celebrating.',anniversary:'Choose a shared memory that feels good to both of you.',thanks:'Name the specific thing you are grateful for.',home:'Think about their space and how they want to settle in.'};
let interest='all';
let active={relationship:'friend',occasion:'just',budget:'all',interest:'all'};
let saved=new Set();
let visible=[];
const $=id=>document.getElementById(id);
function candidates(){
 return gifts.filter(g=>(active.interest==='all'||g.interest===active.interest)&&(active.budget==='all'||(active.budget==='0'?g.min===0:g.max<=Number(active.budget))))
 .sort((a,b)=>Number(b.occasions.includes(active.occasion))-Number(a.occasions.includes(active.occasion)));
}
function render(random=false){
 const matches=candidates();
 if(random&&matches.length>1){const previous=visible[0]?.id;const alternatives=matches.filter(g=>g.id!==previous);visible=[alternatives[Math.floor(Math.random()*alternatives.length)]];}
 else visible=random?matches.slice(0,1):matches.slice(0,6);
 $('result-summary').textContent=random?`One unexpected starting point, within your selections.`:`${visible.length} ideas to start with${matches.length>visible.length?` · ${matches.length} match your selections`:''}. Save a favorite or open the thought behind it.`;
 $('relationship-note').textContent=relationshipNotes[active.relationship]+' '+occasionNotes[active.occasion];
 $('surprise').disabled=matches.length===0;
 $('gift-grid').innerHTML=visible.length?visible.map(g=>`<article class="gift-card"><div class="card-top"><span class="card-category">${g.category}</span><button class="save" data-save="${g.id}" aria-pressed="${saved.has(g.id)}" aria-label="${saved.has(g.id)?'Unsave':'Save'} ${g.title}">${saved.has(g.id)?'Saved ✓':'+ Save'}</button></div><div class="card-body"><p class="budget">${g.max===0?'Use what you have':`Plan roughly $${g.min}–${g.max}`}</p><h3>${g.title}</h3><p>${g.description}</p><details><summary>Why this could feel like them</summary><p>${g.why}</p><p><strong>Before you give:</strong> ${g.check}</p><p><strong>A note to make your own:</strong></p><blockquote>${active.relationship==='colleague'?'Thank you for the way you helped with…':active.relationship==='new'?'You mentioned this the other day, and it made me think of you.':g.note}</blockquote></details></div></article>`).join(''):'<div class="empty"><h3>No ideas in this little collection yet.</h3><p>Try another interest or a wider budget. There is no need to spend more to make a gift meaningful.</p><button class="button secondary" id="reset">Explore all ideas</button></div>';
}
$('interests').addEventListener('click',event=>{const button=event.target.closest('[data-interest]');if(!button)return;interest=button.dataset.interest;for(const item of $('interests').querySelectorAll('button'))item.setAttribute('aria-pressed',String(item===button));});
function applySelections(){active={relationship:$('relationship').value,occasion:$('occasion').value,budget:$('budget').value,interest};}
function focusResults(){ $('ideas-title').focus({preventScroll:true});$('ideas').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}); }
$('gift-form').addEventListener('submit',event=>{event.preventDefault();applySelections();render();focusResults();});
$('surprise').addEventListener('click',()=>{applySelections();render(true);focusResults();});
$('gift-grid').addEventListener('click',event=>{const button=event.target.closest('[data-save]');if(button){const id=button.dataset.save;const title=gifts.find(g=>g.id===id).title;saved.has(id)?saved.delete(id):saved.add(id);button.setAttribute('aria-pressed',String(saved.has(id)));button.setAttribute('aria-label',`${saved.has(id)?'Unsave':'Save'} ${title}`);button.textContent=saved.has(id)?'Saved ✓':'+ Save';$('announcement').textContent=`${title} ${saved.has(id)?'saved for this visit':'removed from saved ideas'}.`;}
 if(event.target.closest('#reset')){$('gift-form').reset();interest='all';for(const button of $('interests').querySelectorAll('button'))button.setAttribute('aria-pressed',String(button.dataset.interest==='all'));applySelections();render();focusResults();}});
$('privacy-open').addEventListener('click',()=>$('privacy').showModal());
$('privacy').querySelector('.dialog-close').addEventListener('click',()=>$('privacy').close());
render();
