import React, {useState, useRef, useEffect, useMemo} from 'react';
import {createRoot} from 'react-dom/client';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {useGSAP} from '@gsap/react';
import {ArrowUpRight, ArrowRight, ArrowLeft, Heart, X, Gift, Sparkle, SlidersHorizontal, Check, Plus, BookmarkSimple} from '@phosphor-icons/react';
import {gifts, interests, intentLabels, initialProfile, rankGifts, selectDiverse, requestedConflict} from './model.js';
import './style.css';
gsap.registerPlugin(ScrollTrigger,useGSAP);
const asset=name=>`./assets/${name}.jpg`;
const money=g=>g.max===0?'Made, not bought':`$${g.min}–${g.max} idea budget`;
const examples=[
 {title:'“We just started dating. I want it to feel thoughtful, not too much.”',detail:'Something personal. A light touch. No grand declarations.',profile:{relationship:'new',intent:'seen',interests:['Coffee & food','Art & making'],evidence:'observed',budget:50}},
 {title:'“They’ve had a long month. I want to make an ordinary day a little softer.”',detail:'Everyday comfort, shaped around what they actually enjoy.',profile:{relationship:'friend',intent:'care',interests:['Home & design','Coffee & food'],evidence:'mentioned',budget:75}},
 {title:'“Another anniversary. Less stuff, more stories we can tell later.”',detail:'Room for a shared experience, if it is something they would choose too.',profile:{relationship:'partner',occasion:'anniversary',intent:'together',interests:['Art & making','Nature & plants'],evidence:'mentioned',budget:120}}
];
function App(){
 const root=useRef(null), resultsRef=useRef(null), finderRef=useRef(null);
 const [profile,setProfile]=useState({...initialProfile}),[applied,setApplied]=useState({...initialProfile});
 const [saved,setSaved]=useState([]),[hidden,setHidden]=useState([]),[feedback,setFeedback]=useState({saved:[],hidden:[]});
 const [modal,setModal]=useState(null),[scenario,setScenario]=useState(0),[gallery,setGallery]=useState(0),[searched,setSearched]=useState(false),[notice,setNotice]=useState('');
 const ranked=useMemo(()=>rankGifts(applied,feedback),[applied,feedback]);
 const results=useMemo(()=>selectDiverse(ranked),[ranked]);
 const change=(key,value)=>setProfile(p=>({...p,[key]:value}));
 const toggleInterest=value=>change('interests',profile.interests.includes(value)?profile.interests.filter(i=>i!==value):[...profile.interests,value]);
 const scrollTo=ref=>{ref.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});ref.current?.focus({preventScroll:true});};
 const find=(event)=>{event?.preventDefault();setApplied({...profile});setFeedback({saved:[...saved],hidden:[...hidden]});setSearched(true);setNotice('Recommendations updated from your selections.');setTimeout(()=>scrollTo(resultsRef),50);};
 const save=id=>{setSaved(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);setNotice(saved.includes(id)?'Removed from your shortlist.':'Saved for this visit. Use “Refine my picks” to apply this preference.');};
 const skip=id=>{setHidden(prev=>[...new Set([...prev,id])]);setFeedback(prev=>({...prev,hidden:[...new Set([...prev.hidden,id])]}));setNotice('Idea hidden for this visit. You can reset feedback.');};
 const selectExample=()=>{setProfile({...initialProfile,...examples[scenario].profile});scrollTo(finderRef);};
 const openGift=id=>setModal({type:'gift',id});
 useGSAP(()=>{
  const mm=gsap.matchMedia();
  mm.add('(prefers-reduced-motion: no-preference)',()=>{
   gsap.from('.hero-copy > *',{y:28,opacity:0,stagger:.11,duration:.8,ease:'power3.out'});
   gsap.from('.hero-object',{y:60,opacity:0,stagger:.12,duration:1,ease:'power3.out'});
   gsap.utils.toArray('.scale-media').forEach(el=>{
    const tl=gsap.timeline({scrollTrigger:{trigger:el,start:'top 95%',end:'bottom top',scrub:true}});
    tl.fromTo(el,{scale:.8,opacity:1},{scale:1,opacity:1,duration:1}).to(el,{opacity:.2,duration:1});
   });
  });
  mm.add('(min-width: 900px) and (prefers-reduced-motion: no-preference)',()=>{
   const cards=gsap.utils.toArray('.story-card');
   cards.slice(0,-1).forEach((card,index)=>{
    ScrollTrigger.create({trigger:card,start:'top 100px',endTrigger:cards[cards.length-1],end:'top 100px',pin:true,pinSpacing:false});
    gsap.to(card,{scale:.95,scrollTrigger:{trigger:cards[index+1],start:'top bottom',end:'top 100px',scrub:true}});
   });
  });
  return ()=>mm.revert();
 },{scope:root});
 useEffect(()=>{const frame=requestAnimationFrame(()=>ScrollTrigger.refresh());return ()=>cancelAnimationFrame(frame);},[results,modal]);
 return <div ref={root}>
 <a className="skip-link" href="#finder">Skip to gift finder</a>
 <header className="nav shell"><a className="brand" href="#"><Gift size={25} weight="light"/><span>little gift finder<span className="brand-dot">.</span></span></a><nav aria-label="Main navigation"><a href="#collection">The gift edit</a><a href="#approach">A little thought</a></nav><button className="shortlist" onClick={()=>setModal({type:'saved'})}><Heart size={18}/> <span>Shortlist</span><b>{saved.length}</b></button></header>
 <main className="overflow-x-hidden w-full max-w-full">
 <section className="hero shell">
  <div className="hero-copy"><p className="eyebrow">FOR WONDERFULLY SPECIFIC PEOPLE</p><h1 className="max-w-6xl">That’s <em>so</em> them.<br/>That’s the gift.</h1><p className="hero-description">A little unusual. A lot more personal.<br/>Find something that says, “I get you.”</p><div className="hero-actions"><a className="button dark" href="#finder">Find their gift <ArrowUpRight size={20}/></a><a className="plain-link" href="#collection">Or wander a little <ArrowRight size={18}/></a></div></div>
  <div className="hero-art" aria-label="Original gift concept collection"><button className="hero-object hero-lamp" onClick={()=>openGift('lamp')} aria-label="Explore the mushroom lamp"><img src={asset('lamp')} alt="Red mushroom lamp concept on a pink background" fetchPriority="high"/><span>A little everyday magic</span></button><button className="hero-object hero-mug" onClick={()=>openGift('mug')} aria-label="Explore the ceramic mug"><img src={asset('mug')} alt="Sculptural blue ceramic cup concept on yellow" fetchPriority="high"/><span>A softer start to the day</span></button><button className="hero-object hero-journal" onClick={()=>openGift('journal')} aria-label="Explore the linen notebook"><img src={asset('journal')} alt="Olive linen notebook and daisy concept"/><span>For their next chapter</span></button></div>
 </section>
 <div className="intro-line shell"><p>Not another endless gift guide.</p><p>A few good ideas. <span>With the thought behind each one.</span></p><ArrowUpRight size={26}/></div>
 <section id="collection" className="collection shell chapter"><div className="section-heading"><h2>Good things.<br/>Better reasons.</h2><p>Little objects that turn “this is nice”<br/>into “you remembered.”</p></div>
  <div className="edit-grid" style={{'--active':gallery}}>{['mug','lamp','journal'].map((id,index)=>{const g=gifts.find(g=>g.id===id);return <button key={id} className={`edit-card ${gallery===index?'expanded':''}`} onMouseEnter={()=>setGallery(index)} onFocus={()=>setGallery(index)} onClick={()=>openGift(id)}><img src={asset(g.image)} alt={g.title} loading="lazy"/><div className="edit-caption"><span>{g.category}</span><h3>{g.title}</h3><span className="circle-arrow"><ArrowUpRight size={23}/></span></div></button>;})}</div><p className="fine-print">Original concept imagery. Gift ideas, not live products for sale.</p>
 </section>
 <section className="scenario shell"><div className="scenario-intro"><span className="small-label">SOUND FAMILIAR?</span><p>Start with the feeling.</p></div><div className="scenario-content" aria-live="polite"><p className="scenario-quote">{examples[scenario].title}</p><p className="muted">{examples[scenario].detail}</p><button className="plain-link" onClick={selectExample}>Find ideas for this moment <ArrowUpRight size={20}/></button></div><div className="carousel-controls"><span>Example {scenario+1} / {examples.length}</span><div><button aria-label="Previous example" onClick={()=>setScenario((scenario+examples.length-1)%examples.length)}><ArrowLeft size={20}/></button><button aria-label="Next example" onClick={()=>setScenario((scenario+1)%examples.length)}><ArrowRight size={20}/></button></div></div></section>
 <section id="finder" ref={finderRef} tabIndex="-1" className="finder-section chapter"><div className="shell finder-layout"><div className="finder-intro"><span className="small-label">A LITTLE ABOUT THEM</span><h2>The best clue?<br/>You know them.</h2><p>Start with what you’ve noticed.<br/>We’ll help connect the dots.</p><img className="finder-image" src={asset('vase')} alt="Cobalt vase with a single daisy" loading="lazy"/></div>
 <form className="finder-form" onSubmit={find}><fieldset><legend>What do you want to say?</legend><div className="intent-options">{Object.entries(intentLabels).map(([key,label])=><button key={key} type="button" aria-pressed={profile.intent===key} onClick={()=>change('intent',key)}>{label}{profile.intent===key&&<Check size={16}/>}</button>)}</div></fieldset>
 <div className="form-row"><label>Who’s it for?<select value={profile.relationship} onChange={e=>change('relationship',e.target.value)}><option value="friend">A good friend</option><option value="new">Someone I’m dating</option><option value="partner">My long-term partner</option><option value="family">Someone in my family</option><option value="colleague">A colleague</option></select></label><label>The occasion<select value={profile.occasion} onChange={e=>change('occasion',e.target.value)}><option value="birthday">Their birthday</option><option value="just">Just because</option><option value="anniversary">An anniversary</option><option value="thanks">A thank-you</option><option value="home">A new home</option></select></label></div>
 <fieldset><legend>What lights them up? <span>Choose any</span></legend><div className="interest-options">{interests.map(interest=><button type="button" key={interest} onClick={()=>toggleInterest(interest)} aria-pressed={profile.interests.includes(interest)}>{profile.interests.includes(interest)?<Check size={15}/>:<Plus size={15}/>} {interest}</button>)}</div></fieldset>
 <div className="form-row"><label>How do you know?<select value={profile.evidence} onChange={e=>change('evidence',e.target.value)}><option value="observed">I’ve seen what they enjoy</option><option value="mentioned">They’ve mentioned these interests</option><option value="guess">It’s a bit of a guess</option></select></label><label>Comfortable budget<select value={profile.budget} onChange={e=>change('budget',Number(e.target.value))}><option value={0}>No spending</option><option value={25}>Up to $25</option><option value={50}>Up to $50</option><option value={75}>Up to $75</option><option value={120}>Up to $120</option></select></label></div>
 <details className="optional"><summary><SlidersHorizontal size={16}/> A specific wish or something to avoid?</summary><label>Have they asked for one of these ideas?<select value={profile.requested} onChange={e=>change('requested',e.target.value)}><option value="">No specific request</option>{gifts.map(g=><option value={g.id} key={g.id}>{g.title}</option>)}</select></label><div className="exclusions">{[['booking','No bookings or fixed dates'],['food','No food or drink gifts']].map(([key,label])=><label key={key}><input type="checkbox" checked={profile.avoid.includes(key)} onChange={()=>change('avoid',profile.avoid.includes(key)?profile.avoid.filter(x=>x!==key):[...profile.avoid,key])}/>{label}</label>)}</div></details>
 <div className="form-end"><span>No account. Just a little thought.</span><button className="button dark" type="submit">Find their gift <ArrowUpRight size={20}/></button></div>
 </form></div></section>
 <section id="results" className="results shell chapter" ref={resultsRef} tabIndex="-1"><div className="results-heading"><div><p className="small-label">{searched?'CHOSEN WITH YOUR ANSWERS':'A FEW PLACES TO START'}</p><h2>{searched?'A little more them.':'See what feels right.'}</h2><p className="muted">{searched?'Your interests, intention and budget, translated into ideas.':'Choose your clues above for more personal suggestions.'}</p></div><div className="results-tools"><button className="button outline" onClick={()=>{setFeedback({saved:[...saved],hidden:[...hidden]});setNotice('Picks refined using your saved and hidden ideas.');}}>Refine my picks <Sparkle size={18}/></button><button className="text-button" onClick={()=>setModal({type:'model'})}>How we choose</button></div></div>
 {requestedConflict(applied)&&<p className="constraint-note" role="status">{requestedConflict(applied)}</p>}
 {feedback.saved.length>0&&<p className="feedback-note">Your saved ideas gently influence these picks. This is feedback from you, not new evidence about them.</p>}
 <div className="result-grid" style={{'--result-columns':Math.max(1,results.length)}}>{results.map(g=><article className="result-card" key={g.id}><div className="result-image"><button className="image-button" onClick={()=>openGift(g.id)} aria-label={`Details for ${g.title}`}><img src={asset(g.image)} alt={`Concept illustration for ${g.title}`} loading="lazy"/></button><button className={`save-button ${saved.includes(g.id)?'is-saved':''}`} aria-label={`${saved.includes(g.id)?'Unsave':'Save'} ${g.title}`} aria-pressed={saved.includes(g.id)} onClick={()=>save(g.id)}><Heart size={21} weight={saved.includes(g.id)?'fill':'regular'}/></button></div><div className="result-meta"><span>{g.exact?'Their specific wish':g.category}</span><span>{money(g)}</span></div><h3><button onClick={()=>openGift(g.id)}>{g.title}</button></h3><p>{g.description}</p><details className="reason"><summary>Why this one <Plus size={15}/></summary><p>{g.reasons[0]}</p>{g.reasons.slice(1).map(r=><p key={r}>{r}</p>)}<p className="uncertainty">{g.uncertainty}</p></details><div className="card-bottom"><button className="plain-link" onClick={()=>openGift(g.id)}>A closer look <ArrowUpRight size={17}/></button><button className="text-button" onClick={()=>skip(g.id)}>Not for them</button></div></article>)}</div>
 {!results.length&&<div className="empty"><h3>No ideas fit these limits yet.</h3><p>We kept your budget and exclusions. Try another setting or clear your hidden ideas.</p><button className="button dark" onClick={()=>scrollTo(finderRef)}>Adjust my choices <ArrowUpRight size={18}/></button></div>}
 {(saved.length>0||hidden.length>0)&&<button className="text-button reset-feedback" onClick={()=>{setSaved([]);setHidden([]);setFeedback({saved:[],hidden:[]});setNotice('Session feedback cleared.');}}>Reset saved and hidden feedback</button>}
 <p className="fine-print">Planning estimates in USD, not seller quotes. Images are AI-created concept illustrations; some ideas share a mood image. Delivery and availability are not verified.</p>
 </section>
 <section id="approach" className="approach shell chapter"><div className="approach-heading"><h2>It’s a gift.<br/>And a little <em>more.</em></h2><div className="approach-note"><img src={asset('letters')} alt="Handwritten letters and dried flowers" loading="lazy"/><div><span className="small-label">A LITTLE EXTRA</span><p>The detail only you can add.</p></div></div></div><div className="stories">
 <article className="story-card peach"><div className="story-copy"><span className="small-label">THE BEAUTY OF PAYING ATTENTION</span><h3>“You remembered<br/>that little thing.”</h3><p>That color they always choose. The hobby they keep talking about. Their coffee, exactly how they like it.</p><p>Our approach starts with those details, rather than guessing from who someone is supposed to be.</p><a className="plain-link" href="#finder">Start with their interests <ArrowUpRight size={19}/></a></div><div className="story-media"><img className="scale-media" src={asset('mug')} alt="A blue cup for a familiar morning ritual" loading="lazy"/></div></article>
 <article className="story-card lilac"><div className="story-copy"><span className="small-label">SOMETHING TO LOOK FORWARD TO</span><h3>A moment can<br/>be the whole gift.</h3><p>A class they’ve wanted to try. A walk with nowhere to rush. An experience they would choose for themselves.</p><p>Gift-giving experiments suggest experiences can strengthen feelings of connection. The person’s preferences still come first.</p><a className="plain-link" href="https://doi.org/10.1093/jcr/ucw067" target="_blank" rel="noreferrer">Read the research <ArrowUpRight size={19}/></a></div><div className="story-media"><img className="scale-media" src={asset('clay')} alt="Pottery tools and handmade bowls for a creative afternoon" loading="lazy"/></div></article>
 </div></section>
 <section className="closing shell chapter"><p className="small-label">FOR YOUR FAVORITE HUMAN</p><h2>Less “what do I buy?”<br/>More <em>“that’s so you.”</em></h2><a className="button dark" href="#finder">Find their gift <ArrowUpRight size={21}/></a></section>
 <footer className="footer shell"><div className="footer-top"><a href="#" className="brand"><Gift size={24}/><span>little gift finder.</span></a><p>A personal project for more thoughtful giving.<br/>Independent of Etsy. No live marketplace connection.</p><div><button className="text-button" onClick={()=>setModal({type:'about'})}>The project</button><button className="text-button" onClick={()=>setModal({type:'privacy'})}>Privacy & credits</button><a href="https://github.com/sylarchan91/little-gift-finder/issues" target="_blank" rel="noreferrer">Get in touch <ArrowUpRight size={14}/></a></div></div><div className="footer-bottom"><span>Made with a little thought.</span><span>Ideas over algorithms. People over profiles.</span></div></footer>
 </main><div className="sr-only" role="status">{notice}</div>
 {modal&&<Modal modal={modal} close={()=>setModal(null)} saved={saved} save={save} openGift={openGift} ranked={ranked} profile={applied}/>}
 </div>;
}
function Modal({modal,close,saved,save,openGift,ranked,profile}){
 const dialog=useRef(null);
 useEffect(()=>{dialog.current.showModal();return ()=>dialog.current?.close();},[]);
 const g=modal.type==='gift'?(ranked.find(g=>g.id===modal.id)||gifts.find(g=>g.id===modal.id)):null;
 return <dialog ref={dialog} className={`modal ${g?'gift-modal':''}`} onCancel={close} onClick={e=>{if(e.target===dialog.current)close();}} aria-label={g?g.title:modal.type==='saved'?'Your shortlist':'Project information'}><button className="modal-close" onClick={close} aria-label="Close dialog"><X size={23}/></button>
 {g?<div className="gift-detail"><img src={asset(g.image)} alt={`Concept illustration for ${g.title}`}/><div><p className="small-label">{g.category}</p><h2>{g.title}</h2><p className="detail-budget">{money(g)}</p><p>{g.description}</p><h3>The thought behind it</h3>{g.reasons?g.reasons.map(r=><p key={r}>{r}</p>):<p>{g.max>profile.budget?'This idea is above your current planning budget, so it was excluded from your recommendations.':'This editorial idea is outside your current picks. Review any exclusions or hidden feedback before choosing it.'}</p>}<h3>Before you give</h3><p>{g.watch}</p><h3>A note to make your own</h3><blockquote>{g.note}</blockquote><button className="button dark" onClick={()=>save(g.id)}><Heart size={18} weight={saved.includes(g.id)?'fill':'regular'}/>{saved.includes(g.id)?'Saved to shortlist':'Save this idea'}</button><p className="fine-print">Illustrative concept, not a product listing. No live pricing or delivery information.</p></div></div>:
 modal.type==='saved'?<><span className="small-label">ONLY FOR THIS VISIT</span><h2>Your little shortlist.</h2>{saved.length?<><p>Use “Refine my picks” to let these choices gently inform your next recommendations.</p><div className="saved-list">{gifts.filter(g=>saved.includes(g.id)).map(g=><div key={g.id}><button onClick={()=>openGift(g.id)}><img src={asset(g.image)} alt=""/><span>{g.title}<small>{money(g)}</small></span></button><button aria-label={`Remove ${g.title}`} onClick={()=>save(g.id)}><X size={18}/></button></div>)}</div></>:<div className="empty"><BookmarkSimple size={42} weight="light"/><p>Nothing here yet. Save an idea that makes you think of them.</p><button className="button dark" onClick={close}>Keep exploring <ArrowRight size={18}/></button></div>}</>:
 modal.type==='model'?<><h2>A little logic.<br/>No mind reading.</h2><p>We first keep ideas inside your budget and exclusions. A specific requested idea takes priority if it passes those limits.</p><p>Then we consider interests and the evidence behind them, what you want to express, relationship context, everyday usefulness and occasion. Novelty is a small bonus.</p><p>We lower the priority of intense gestures in early or formal relationships, and unfamiliar experiences when preferences are uncertain. A few varied directions keep the results from becoming four of the same thing.</p><p>Saved ideas add a small preference signal only when you refine. Hidden ideas stay out until you reset feedback.</p><p>These are editorial rules, not a clinically validated model or a probability of making someone happy. No quality, shipping or popularity scores are invented.</p><a href="https://github.com/sylarchan91/little-gift-finder/blob/main/MODEL.md" target="_blank" rel="noreferrer">Read the scoring rules <ArrowUpRight size={16}/></a></>:
 modal.type==='about'?<><h2>For the joy of getting someone.</h2><p>Little Gift Finder is a personal coding project exploring how interests, relationships and intentions can make gift ideas more relevant.</p><p>This version uses 12 editorial concepts, original AI-created illustrations and transparent recommendation rules. It has no paid features, checkout or affiliate links.</p><p>A future Etsy integration is planned, subject to approval, to show public listing titles, images, prices and shop details with links back to Etsy. It is not connected or approved yet.</p><p>This application is not endorsed or certified by Etsy, Inc. Etsy is a trademark of Etsy, Inc.</p><h3>Reading behind the approach</h3><p><a href="https://doi.org/10.1093/jcr/ucw067" target="_blank" rel="noreferrer">Chan & Mogilner: experiential gifts and relationship strength.</a> A group-level finding, not a promise for a particular relationship.</p><p><a href="https://www.gottman.com/blog/small-actions-make-big-impacts/" target="_blank" rel="noreferrer">The Gottman Institute: responding to everyday bids for connection.</a> Applying this to gift choices is our interpretation.</p></>:
 <><h2>Privacy & credits.</h2><p>No accounts, advertising, analytics or cookies set by this application. Answers, saves and hidden ideas stay in memory in this tab and disappear on reload.</p><p>All images, fonts and application files are hosted with the site. GitHub Pages may process standard request information under <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" target="_blank" rel="noreferrer">GitHub’s privacy statement</a>. External links follow their own policies.</p><p>Images are original AI-generated gift concepts, not seller photography. Some concepts use a shared mood illustration. Prices are planning estimates; no stock, quality or delivery claims are made.</p><p>Typography: Satoshi by Indian Type Foundry, via Fontshare. Icons: Phosphor. Motion: GSAP. Relationship content offers general ideas, not diagnosis, therapy or guaranteed outcomes.</p><p>Updated September 10, 2026.</p></>}
 </dialog>;
}
createRoot(document.getElementById('root')).render(<App/>);
